### ISSUE TITLE
parseQuery requires string

### ISSUE THREAD

**Issue by Noitidart** [EventMobi/regexp-replace-loader#1]
```
loaders: [

{ test:/\.js$/, loader:'regexp-replace-loader', query:{match:{pattern:'^.*?console\.[a-zA-Z].*?$', flags:'gm'}, replaceWith:''}, enforce:'pre' }

],
```

Is giving me: `Module build failed: Error: parseQuery should get a string as first argument
    at Object.parseQuery (C:\Users\Mercurius\Desktop\Trigger\node_modules\regexp-replace-l
oader\node_modules\loader-utils\index.js:48:9) 

Also aside: webpack requires we use `-loader` suffix now, so that was throwing too.

**Comment by elliottsj** [comment]
#2 should fix this issue. In the meantime, you can wrap your `query` object in a `JSON.stringify()`, which should avoid the parseQuery error:
```js
query: JSON.stringify({match:{pattern:'^.*?console\.[a-zA-Z].*?$', flags:'gm'}, replaceWith:''})
```

**Comment by Noitidart** [comment]
Thanks very much for the super fast reply! Will try that out! :)
